export const MUG_COLLECTION = {
    mug_1: {
        img: "../mug_images/floral1.jpg",
        name: "Floral Mug",
        price: 24.99,
        artist: "Helen Kirst",
        description: "Handmade in Brooklyn, NY",
        pic_1: "../mug_images/floral4.jpg",
        pic_2: "../mug_images/floral3.jpg",
        review_num: 50,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star1.jpg",
        star4:"../starRatings/star.png",
        star5:"../starRatings/star.png"
    },
    mug_2: {
        img: "../mug_images/orangeMug.jpg",
        name: "Dots Mug",
        price: 25.99,
        artist: "Steven Olwedo",
        description: "Handmade in Bronx, NY",
        pic_1: "../mug_images/greenDot.jpg",
        pic_2: "../mug_images/yellowDot.jpg",
        review_num: 10,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star1.jpg",
        star4:"../starRatings/star1.jpg",
        star5:"../starRatings/star.png"
    },
    mug_3: {
        img: "../mug_images/faces1.jpg",
        name: "Faces Mug",
        price: 34.25,
        artist: "Rowena Halpstone",
        description: "Handmade in Oakland, CA",
        pic_1: "../mug_images/faces2.jpg",
        pic_2: "../mug_images/faces3.jpg",
        review_num: 22,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star.png",
        star4:"../starRatings/star.png",
        star5:"../starRatings/star.png"
    },
    mug_4: {
        img: "../mug_images/rainbow1.jpg",
        name: "Rainbow Mug",
        price: 35.99,
        artist: "Susan Kappala",
        description: "Handmade in Pheonix, AZ",
        pic_1: "../mug_images/rainbow2.jpg",
        pic_2: "../mug_images/rainbow3.jpg",
        review_num: 45,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star.png",
        star4:"../starRatings/star.png",
        star5:"../starRatings/star.png"
    },
    mug_5: {
        img: "../mug_images/cone1.jpg",
        name: "Cone Mug",
        price: 13.99,
        artist: "Devante Richardson",
        description: "Handmade in Denver, CO",
        pic_1: "../mug_images/cone2.jpg",
        pic_2: "../mug_images/cone3.jpg",
        review_num: 88,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star1.jpg",
        star4:"../starRatings/star1.jpg",
        star5:"../starRatings/star1.jpg"
    },
    mug_6: {
        img: "../mug_images/summer1.jpg",
        name: "Summertime Sunshine Mug",
        price: 23.99,
        artist: "Julie Shay",
        description: "Handmade in Austin, TX",
        pic_1: "../mug_images/summer2.jpg",
        pic_2: "../mug_images/summer3.jpg",
        review_num: 12,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star1.jpg",
        star4:"../starRatings/star.png",
        star5:"../starRatings/star.png"
    },
    mug_7: {
        img: "../mug_images/blue1.jpg",
        name: "Turquoise Mug",
        price: 40.99,
        artist: "Andrew Ludwig",
        description: "Handmade in San Francisco, CA",
        pic_1: "../mug_images/blue2.jpg",
        pic_2: "../mug_images/blue3.jpg",
        review_num: 50,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star.png",
        star4:"../starRatings/star.png",
        star5:"../starRatings/star.png"
    },
    mug_8: {
        img: "../mug_images/green1.jpg",
        name: "Lilypad Mug",
        price: 54.99,
        artist: "Andrew Ludwig",
        description: "Handmade in San Francisco, CA",
        pic_1: "../mug_images/green2.jpg",
        pic_2: "../mug_images/green3.jpg",
        review_num: 32,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star1.jpg",
        star4:"../starRatings/star1.jpg",
        star5:"../starRatings/star1.jpg"
    },
    mug_9: {
        img: "../mug_images/garden1.jpg",
        name: "Garden Mug",
        price: 28.99,
        artist: "Lucy Treleon",
        description: "Handmade in Albany, NY",
        pic_1: "../mug_images/garden2.jpg",
        pic_2: "../mug_images/garden3.jpg",
        review_num: 12,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star1.jpg",
        star4:"../starRatings/star.png",
        star5:"../starRatings/star.png"
    },
    mug_10: {
        img: "../mug_images/geometric1.jpg",
        name: "Geometric Mug",
        price: 45.99,
        artist: "Dale Thompson",
        description: "Handmade in San Jose, CA",
        pic_1: "../mug_images/geometric2.jpg",
        pic_2: "../mug_images/geometric3.jpg",
        review_num: 54,
        star1:"../starRatings/star1.jpg",
        star2:"../starRatings/star1.jpg",
        star3:"../starRatings/star1.jpg",
        star4:"../starRatings/star.png",
        star5:"../starRatings/star.png"
    }
    
}
